theme: jekyll-theme-minimal
markdown: kramdown
	  parse_block_html: true
title: Software for Communities
description: Connecting people with the resources that they need across languages.
highlighter: rouge